php:
  image: yiisoftware/yii2-php:7.1-apache
  volumes:
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ./:/app:delegated
  ports:
    - '8000:80'
  links:
    - mysql

mysql:
  image: mysql:5.7
  ports:
    - "33060:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pokemon
    - MYSQL_DATABASE=pokemon
